config/routes.rb
Medvane::Application.routes.draw do |map|
  resources :articles, :journals, :authors, :subjects, :pubtypes, :genes do
    member do
      get :one, :five, :ten, :all
    end
    collection do
      get :one, :five, :ten, :all
    end
  end

  root :to => "home#all"
  match "/all" => "home#all", :as => "all_home"
  match "/one" => "home#one", :as => "one_home"
  match "/five" => "home#five", :as => "five_home"
  match "/ten" => "home#ten", :as => "ten_home"
  
  match '/code', :to => redirect("http://github.com/medvane/solo")
  match '/bugs', :to => redirect("http://github.com/medvane/solo/issues")

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :journal
  has_many :authorships
  has_many :authors, :through => :authorships, :order => "authorships.position"
  has_many :article_types
  has_many :pubtypes, :through => :article_types
  has_many :published_genes
  has_many :genes, :through => :published_genes
  has_many :subjects, :class_name => 'Topic', :include => :subject
  #has_many :subjects, :through => :topics
  
  def self.search(query, options = {})
    options[:page]      ||= 1
    options[:per_page]  ||= 10
    options[:order]     ||= "pubdate desc"
    options[:include]   ||= :journal
    paginate options
  end

  def to_s
    title
  end
end

app/models/article_type.rb
class ArticleType < ActiveRecord::Base
  belongs_to :article
  belongs_to :pubtype
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # GET /articles
  def index(period = "all")
    total_entries = BibliomeStat.last_cached.send("#{period}_articles")
    per_page = per_page(total_entries, 14)
    @articles = Article.search params[:q], :page => params[:page], :per_page => per_page, :total_entries => total_entries

    respond_to do |format|
      format.html { render :action => "index"}
    end
  end

  # GET /articles/1
  def show(period = "all")
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html  { render :action => "show"}
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def citation(article, period = 'all')
    journal = content_tag(:em, article.journal.to_s)
    citation = link_to(journal + " #{article.pubdate.year}", journal_path(article.journal).html_safe + '/' + period)
    content_tag(:span, citation.html_safe, :class => "citation")
  end
end

app/views/articles/index.html.erb
<h1>Articles</h1>
<div id="charts">

<%= publication_history(ArticleStat.all) %>

</div>
<%= paginated_list @articles, @period %>

app/views/articles/show.html.erb
<% page_title "Article: " + @article.to_s %>

<h1><%= @article.to_s %> <%= citation @article, @period %></h1>
<div class="yui-gc">
  <div class="yui-u first">

<div class="affiliation"><%= @article.affiliation %></div>
<div class="abstract"><%= @article.abstract %></div>

<%= content_tag(:span, link_to("See PubMed record in a new window", "http://www.ncbi.nlm.nih.gov/sites/entrez/" + @article.id.to_s, :target => "_blank"), :class => "citation") %>
  </div><!-- .yui-u .first -->
  <div class="yui-u">
<% if @article.authors.size > 0 -%>
<h2>Authors</h2>
<ul>
<% for author in @article.authors -%>
  <li><%= link_to author.to_s, author_path(author) + "/#{@period}" %></li>
<% end -%>
</ul>
<% end -%>
<% if @article.subjects.size > 0 -%>
<h2>Subjects</h2>
<ul>
<% for subject in @article.subjects.select {|s| s.major_topic == true } -%>
  <li><%= link_to subject.subject.to_s, subject_path(subject.subject) + "/#{@period}" %></li>
<% end -%>
</ul>
<% end -%>
<% if @article.genes.size > 0 -%>
<h2>Genes</h2>
<ul>
<% for gene in @article.genes -%>
  <li><%= link_to gene.to_s, gene_path(gene) + "/#{@period}" %></li>
<% end -%>
</ul>
<% end -%>
<% if @article.pubtypes.size > 0 -%>
<h2>Pubtypes</h2>
<ul>
<% for pubtype in @article.pubtypes -%>
  <li><%= link_to pubtype.to_s, pubtype_path(pubtype) + "/#{@period}" %></li>
<% end -%>
</ul>
<% end -%>

  </div><!-- .yui-u -->
</div><!-- .yui-ge -->